apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: adcs-issuer-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: adcs-issuer-webhook-service
      namespace: cert-manager
      path: /validate-adcs-certmanager-csf-nokia-com-v1-adcsissuer
  failurePolicy: Fail
  name: adcsissuer-validation.adcs.certmanager.csf.nokia.com
  rules:
  - apiGroups:
    - adcs.certmanager.csf.nokia.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - adcsissuer
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: adcs-issuer-webhook-service
      namespace: cert-manager
      path: /validate-batch-certmanager-csf-nokia-com-v1-clusteradcsissuer
  failurePolicy: Fail
  name: vclusteradcsissuer.kb.io
  rules:
  - apiGroups:
    - batch.certmanager.csf.nokia.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusteradcsissuers
  sideEffects: None
