apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "chart.fullname" . }}-serving-cert
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  commonName: $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
  dnsNames:
  - '{{ include "chart.fullname" . }}-$(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.{{ .Values.kubernetesClusterDomain
    }}'
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
  secretName: webhook-server-cert