apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adcs-issuer-cert-manager-controller-approve:adcs-certmanager-csf-nokia-com
rules:
- apiGroups:
  - cert-manager.io
  resourceNames:
  - adcsissuers.adcs.certmanager.csf.nokia.com/*
  - clusteradcsissuers.adcs.certmanager.csf.nokia.com/*
  resources:
  - signers
  verbs:
  - approve
