# permissions to approve all adcs.certmanager.csf.nokia.com requests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-approve:adcs-certmanager-csf-nokia-com
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - signers
  verbs:
  - approve
  resourceNames:
  - adcsissuers.adcs.certmanager.csf.nokia.com/*
  - clusteradcsissuers.adcs.certmanager.csf.nokia.com/*
