# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: master
chart-dirs:
  - charts
chart-repos:
  - adcs-issuer=https://djkormo.github.io/adcs-issuer/
  - cert-manager=https://charts.jetstack.io
helm-extra-args: --timeout 300s
