apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adcs-certificate
spec:
  commonName: test.example.com
  dnsNames:
  - test1-alternate.example.com
  - test2-alternate.example.com
  issuerRef:
    group: adcs.certmanager.csf.nokia.com
    kind: AdcsIssuer
    name: test-adcs-issuer
    
  secretName: adcsIssuer-certificate