apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: adcs-cert
  namespace: cert-manager
spec:
  commonName: example.com
  dnsNames:
  - service1.example.com
  - service2.example.com
  issuerRef:
    group: adcs.certmanager.csf.nokia.com
    kind: ClusterAdcsIssuer
    name: adcsclusterissuer-sample 
  secretName: webhook-server-cert
#  subject:
#    organizations:
#      - example.com
#      - anybody.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: generic-cert
  namespace: cert-manager
spec:
  commonName: example.com
  dnsNames:
  - service1.example.com
  - service2.example.com
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert