apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: adcs-issuer-cert-manager-controller-approve:adcs-certmanager-csf-nokia-com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: adcs-issuer-cert-manager-controller-approve:adcs-certmanager-csf-nokia-com
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
