{{- if .Values.metricsService.enabled }}
apiVersion: v1
kind: Service
metadata:
{{- $metricsServiceName := printf "%s-controller-metrics" (include "chart.fullname" . | trunc 44) }}
  name: {{ default $metricsServiceName $.Values.metricsService.nameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type | default "ClusterIP" }}
  selector:
    control-plane: controller-manager
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.metricsService.ports | toYaml | nindent 4 }}
{{- end }}
