name: Lint and Test Charts

on: 
  - pull_request
  - workflow_dispatch

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1 
        with:
          fetch-depth: 0


      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.13.0

      - name: Setup polaris
        uses: fairwindsops/polaris/.github/actions/setup-polaris@master
       
        with:
          version: 9.5.0

      - name: Setup Pluto
        uses: FairwindsOps/pluto/github-action@master

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        continue-on-error: true
        id: list-changed
        run: |
          changed=$(ct list-changed --config ./.github/configs/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Run chart-testing (lint)
        continue-on-error: true
        run: |
          pwd 
          ct lint --config ./.github/configs/ct.yaml --lint-conf ./.github/configs/lintconf.yaml --chart-yaml-schema ./.github/configs/chart_schema.yaml --debug 

      - name: Create kind cluster
        continue-on-error: true
        uses: helm/kind-action@v1.10.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          config: .github/configs/kind-config.yaml

      - run: |
          echo "Install cert-manager and so on ..."
          kubectl cluster-info 
          kubectl get nodes -v=6
          helm version 
          helm repo add jetstack https://charts.jetstack.io --force-update
          helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.14.2  --set installCRDs=true --set enableCertificateOwnerRef=true
          helm repo add fairwinds-stable https://charts.fairwinds.com/stable --force-update
          helm upgrade --install polaris fairwinds-stable/polaris --namespace demo --create-namespace --set webhook.enable=false --set dashboard.enable=false
          kubectl get nodes -o wide 
        

      - name: Use polaris for checking helm chart manifests
        continue-on-error: true
        run: |
          pwd 
          polaris audit --helm-chart ${GITHUB_WORKSPACE}/charts/adcs-issuer  --helm-values ${GITHUB_WORKSPACE}/charts/adcs-issuer/values.yaml --format=pretty --quiet --only-show-failed-tests
        
      - name: Use pluto for checking helm chart manifests
    
        continue-on-error: true
        run: |
          pwd 
          helm template ${GITHUB_WORKSPACE}/charts/adcs-issuer --values ${GITHUB_WORKSPACE}/charts/adcs-issuer/values.yaml | pluto detect --target-versions k8s=v1.27.0 -v 2 -o wide -
          helm template ${GITHUB_WORKSPACE}/charts/adcs-issuer --values ${GITHUB_WORKSPACE}/charts/adcs-issuer/values.yaml | pluto detect --target-versions k8s=v1.28.0 -v 2 -o wide -
          helm template ${GITHUB_WORKSPACE}/charts/adcs-issuer --values ${GITHUB_WORKSPACE}/charts/adcs-issuer/values.yaml | pluto detect --target-versions k8s=v1.29.0 -v 2 -o wide -
          helm template ${GITHUB_WORKSPACE}/charts/adcs-issuer --values ${GITHUB_WORKSPACE}/charts/adcs-issuer/values.yaml | pluto detect --target-versions k8s=v1.30.0 -v 2 -o wide -
          helm template ${GITHUB_WORKSPACE}/charts/adcs-issuer --values ${GITHUB_WORKSPACE}/charts/adcs-issuer/values.yaml | pluto detect --target-versions k8s=v1.31.0 -v 2 -o wide -

      - name: Run chart-testing (install)
        continue-on-error: true
        run: ct install --config ./.github/configs/ct.yaml 

