apiVersion: v1
kind: Service
metadata:
  name: adcs-issuer-webhook-service
  namespace: cert-manager
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
